<?php

namespace App\Form;

use App\Entity\JobSeeker;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JobSeekerRegistrationType extends RegistartionType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // TODO: Change the autogenerated stub
    }

    public function configureOptions(OptionsResolver $resolver)
     {
         $resolver->setDefaults([
             "data_class" => JobSeeker::class
         ]);
     }

    public function getBlockPrefix()
    {
        return "job_seeker_form"; //
    }




}