<?php

declare(strict_types=1);

namespace App\Form;

use App\Entity\Recruiter;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RecruiterRegistrationType extends RegistartionType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options); // Call the parent method to add common fields
       $builder->add('companyName', null, [
            'label' => 'Company Name',
            'required' => false,
            'attr' => ['maxlength' => 255],
        ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            "data_class" => Recruiter::class
        ]);
    }

    public function getBlockPrefix()
    {
        return "recruiter_form"; // TODO: Change the autogenerated stub
    }
}
